version: '3'
services:
  proxy:
    build: ./proxy
    environment:
      - URL=${DOMAIN}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=http
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Berlin
      - STAGING=true
      - ONLY_SUBDOMAINS=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/director/proxy:/config
    cap_add:
      - NET_ADMIN
    restart: always
  test:
    image: nginx
