- name: apt udpate and upgrade
  apt:
    upgrade: full
    update_cache: yes
    force_apt_get: yes

- name: check if swap is on
  shell: swapon -s --noheadings --show=NAME | wc -l
  register: swaps
  changed_when: False
- name: deactivate swap for this session
  shell: swapoff -a
  when: swaps.stdout != '0'
- name: deactivate swap for all other sessions
  lineinfile:
    path: /etc/fstab
    regexp: '^(?!#).*swap'
    state: absent

- name: install apt-https
  apt:
    name: apt-transport-https
    state: present
- name: Add the docker apt key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    id: 0EBFCD88
- name: Add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
    state: present
    filename: docker
- name: Install docker-ce
  apt:
    name: docker-ce
    state: present

- name: Add the kubernetes key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: Add kubernetes repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes
- name: install kubelet kubeadm kubectl
  apt:
    name: "{{item}}"
  loop:
    - kubeadm
    - kubectl
    - kubelet