- name: pull kubernetes images
  shell: kubeadm config images pull
- name: create kubeadm config
  template:
    src: kubeadm_config.yml
    dest: kubeadm_config.yml
- stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf
- block:
    - name: do the kubeinit
      shell: kubeadm init --config kubeadm_config.yml
      register: init_err
    - name: create .kube dir
      file: path=~/.kube state=directory
    - name: copy admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        remote_src: yes
    - name: apply kubenet addons 
      shell: "kubectl apply -f {{item}}"
      loop: "{{pod_network_addons}}"
      register: apply_err
  rescue:
    - shell: kubeadm reset -f
    - file: path=~/.kube state=absent
    - local_action: copy content={{ init_err.results | map(attribute='stderr') | join('\n\n') }} dest=init_error.log unsafe_writes=yes
      when: "{{init_err.failed}}"
    - debug: msg={{apply_err}}
    - local_action: copy content={{ apply_err.results | map(attribute='stderr') | join('\n\n') }} dest=apply_error.log unsafe_writes=yes
      when: apply_err.failed
    - fail:
        msg: "Kubeadm init failed. Executed a reset. Log written to local disk"
  when: not admin_conf.stat.exists